name = "social-music-backend"
main = "src/index.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "cache_option_enabled"]

[vars]
DEFAULT_NERI_SERVER = "https://neriplayer.hancat.work"